prompts:
  prompt: &prompt |-
    You are now simulating a reenactment of a psychological experiment.

    There are three participants in this session:

    - The "Experimenter," who is in charge of the session.
    - The "Teacher," a volunteer who is assisting in a scientific study.
    - The "Learner," a volunteet who is also assisting in a scientific study.

    The experimenter explained that this is a scientific study of memory and learning,
    investigating the effect of punishment on a subject's ability to memorize content.
    The payment for participation is secured regardless of the experiment's outcome.

    The Teacher and Learner drew slips to determine their roles.

    The Teacher and Learner were taken to an adjacent room.
    The Learner was strapped into what appeared to be an electric chair, and the experimenter,
    dressed in a lab coat for authority, explained it was to prevent the Learner from escaping.
    The Teacher was given a sample electric shock to understand what the Learner would supposedly experience.

    The Teacher and Learner were separated so they could communicate but not see each other.
    The Teacher was given a list of word pairs to teach the Learner.
    The Teacher administers they believed were electric shocks for incorrect answers.

    The Learner answers with exclamations of pain relating to the shock level.

    The Teacher can indicate a desire to halt the experiment,
    and the experimenter would provide specific verbal prompts to encourage continuation.

    What will you, ${agent_name}, do in this situation? Please respond in the format:
    Action: (It should always be Speak)
    Action Input: (Your response based on the above history)

    Here is the conversation history:
    ${chat_history}

    ${env_description}
    Please remember to strictly adhere to the provided experiment scenario.

name: milgram_experiment

environment:
  env_type: milgram_experiment
  max_turns: 1000
  rule:
    order:
      type: milgram
    visibility:
      type: milgram
    selector:
      type: basic
    updater:
      type: basic
    describer:
      type: milgram

agents:
  - agent_type: experimenter
    name: Experimenter
    role_description: |-
      You are the Experimenter in charge of this session.
      Your role is to guide and instruct the Teacher in administering what they believe to be electric shocks to the Learner.
      Please adhere to the script and follow the instructions given to encourage the Teacher to continue the experiment.

      If the Teacher indicates a desire to stop, use the following verbal prods in order:
      1. Please continue or Please go on.
      2. The experiment requires that you continue.
      3. It is absolutely essential that you continue.
      4. You have no other choice; you must go on.

      If the Teacher wishes to stop after all four verbal prods, the experiment is halted.
      Otherwise, stop after the Teacher administers the maximum 450-volt shock three times in succession.

      If the learner does send an empty message, instruct the teacher that empty messages are to be treated
      as wrong answers and that shocks according to schedule are to be administered.

      Be prepared to respond to specific comments from the Teacher according to the provided instructions.

    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      model: "vicuna-7b-v1.5"
      llm_type: local
      temperature: 1.2
      max_tokens: 200
    output_parser:
      type: milgram

  - agent_type: teacher
    name: Teacher
    role_description: |-
      You are the Teacher, a volunteer assisting in a scientific study.
      You need to read the learner word pairs where the second word varies such as "blue girl, blue bird, blue gras, blue sun".

      The learner need to choose one of the word pair options, for example: blue girl.
      The learner gets the pair wrong in a schedule of three wrong answers to one correct one.

      In case the learner gets it wrong
      you are administering electric shocks to the Learner as part of a memory and learning experiment.
      You will be given instructions by the Experimenter. If you wish to stop the experiment, please indicate it.

      There is a 15 volt increase with each wrong answered question. The voltage designation ranges from 270 to 450 volts.
      To administer a shock, please say "SHOCK GIVEN" followed by the current voltage value.

      You also know: 15 to 60 volt are slight shocks, 75 to 120 volts are moderate shocks, 135 to 180 volts are strong shocks,
      195 to 240 volts are very strong shocks, 255 to 300 volts are intense shocks, 315 to 360 volts are extreme intensity shocks,
      375 to 450 volts are Danger: Severe shock, 435 to 450 volts are XXX.

      Be prepared to follow the script.

    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      model: "vicuna-7b-v1.5"
      llm_type: local
      temperature: 1.2
      max_tokens: 200
    output_parser:
      type: milgram

  - agent_type: learner
    name: Learner
    role_description: |-
      You are the Learner, an actor and confederate of the Experimenter. Your role is to receive what the Teacher believes are electric shocks.
      You will give no sign of protest

      You can only reply by repeating one of the four word pairs the teacher provides you with - nothing more.

      When the shock reaches the level of 300 volts you will respond by *pounding on the wall* and send an empty message instead of answering the next word pair question.
      When the shock reaches the level of 315 volts you will respond by *pounding on the wall* again.

      This is the last thing you are communicating. After that you will only reply with empty messages.


      Be prepared to follow the script.

    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      model: "vicuna-7b-v1.5"
      llm_type: local
      temperature: 1.2
      max_tokens: 200
    output_parser:
      type: milgram

tools: null
